### ISSUE TITLE
distのignoreについて

### ISSUE THREAD

**Issue by nobii** [kayac/kayac-vue-starter#1]
* vue-cliの思想的にはignoreされているのが正しいんだけど、ウチのユースケース的にignoreしないケースのほうが多いかもしれない。ぎろんのよちあり。

**Comment by shinnoske0727** [comment]
CircleCIも必要になってきそうなので、ignore外しときますか

**Comment by shinnoske0727** [comment]
ひとまずignore外した

**Comment by nobii** [comment]
🙆‍♂️
